name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.1
  dotenv: ^4.2.0
  chatterbox:
    path: ../
  functions_framework: ^0.4.3+1
  firedart: ^0.9.7

dev_dependencies:
  build_runner: ^2.4.8
  functions_framework_builder: ^0.4.10
  lints: ^2.0.0
  test: ^1.21.0
