name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3

dependencies:
  dotenv: ^4.2.0

  chatterbox:
    path: ../

  # Networking
  functions_framework: ^0.4.0
  shelf: ^1.4.1

dev_dependencies:

  # Code generation
  build_runner: ^2.4.7
  functions_framework_builder: ^0.4.10
