name: chatterbox
description: Framework to build dialog flows for Telegram Bots
version: 1.7.1
repository: https://dart.dev/tools/pub/publishing

environment:
  sdk: ^3.0.5

dependencies:
  # APIs
  televerse: ^1.15.12

  # Utils
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0